
package com.UI;

import com.controlers.Controler;
import com.dao.Connect;
import com.dao.DateToString;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rishi
 */
public class Payment extends javax.swing.JFrame {

    
    private Integer amount_value,activity_id,supplier_id,quantity,total;
    private String med,exp,act_date;
    private String[] modetype={"CASH","CARD","CHEQUE"};
    private int PayFlag;
    public Payment() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mode = new javax.swing.JComboBox<>();
        cardDesk = new javax.swing.JPanel();
        cash = new javax.swing.JPanel();
        cashPay = new javax.swing.JLabel();
        card = new javax.swing.JPanel();
        cardPay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cardNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bankName = new javax.swing.JTextField();
        CardType = new javax.swing.JComboBox<>();
        cheque = new javax.swing.JPanel();
        chequePay = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chequeNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cBankName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pay_Date = new com.toedter.calendar.JDateChooser();
        Close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(102, 179, 255));
        Background.setPreferredSize(new java.awt.Dimension(410, 400));

        Title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Payment");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Amount:");

        amount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        amount.setToolTipText("Amount has to pay");
        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Payment Mode:");

        mode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CARD", "CHEQUE" }));
        mode.setBorder(null);
        mode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modeItemStateChanged(evt);
            }
        });

        cardDesk.setLayout(new java.awt.CardLayout());

        cash.setBackground(new java.awt.Color(255, 255, 255));

        cashPay.setBackground(new java.awt.Color(102, 179, 255));
        cashPay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cashPay.setForeground(new java.awt.Color(255, 255, 255));
        cashPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashPay.setText("Pay");
        cashPay.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), null));
        cashPay.setOpaque(true);
        cashPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashPayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cashLayout = new javax.swing.GroupLayout(cash);
        cash.setLayout(cashLayout);
        cashLayout.setHorizontalGroup(
            cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(cashPay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        cashLayout.setVerticalGroup(
            cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(cashPay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        cardDesk.add(cash, "card2");

        card.setBackground(new java.awt.Color(255, 255, 255));

        cardPay.setBackground(new java.awt.Color(102, 179, 255));
        cardPay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cardPay.setForeground(new java.awt.Color(255, 255, 255));
        cardPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardPay.setText("Pay");
        cardPay.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), null));
        cardPay.setOpaque(true);
        cardPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardPayMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Card Type:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Card Number:");

        cardNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cardNumber.setToolTipText("Enter a card number");
        cardNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cardNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Bank Name:");

        bankName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bankName.setToolTipText("Enter a bank name");
        bankName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CREDIT", "DEBIT" }));
        CardType.setToolTipText("Select Card Type");

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cardNumber))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(CardType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(bankName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(cardPay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardLayout.createSequentialGroup()
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(cardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(cardPay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cardDesk.add(card, "card2");

        cheque.setBackground(new java.awt.Color(255, 255, 255));

        chequePay.setBackground(new java.awt.Color(102, 179, 255));
        chequePay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        chequePay.setForeground(new java.awt.Color(255, 255, 255));
        chequePay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chequePay.setText("Pay");
        chequePay.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), null));
        chequePay.setOpaque(true);
        chequePay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chequePayMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Cheque Number:");

        chequeNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chequeNumber.setToolTipText("Enter a cheque number");
        chequeNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Bank Name:");

        cBankName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cBankName.setToolTipText("Enter a bank name");
        cBankName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout chequeLayout = new javax.swing.GroupLayout(cheque);
        cheque.setLayout(chequeLayout);
        chequeLayout.setHorizontalGroup(
            chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chequeLayout.createSequentialGroup()
                .addGroup(chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chequeLayout.createSequentialGroup()
                        .addGroup(chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chequeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(cBankName)))
                    .addGroup(chequeLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(chequePay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        chequeLayout.setVerticalGroup(
            chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chequeLayout.createSequentialGroup()
                .addGroup(chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chequeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(chequePay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        cardDesk.add(cheque, "card2");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardDesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Pay_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(Pay_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(cardDesk, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/Icons/icons8_Multiply_32px.png"))); // NOI18N
        Close.setToolTipText("Close ");
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close)
                .addGap(18, 18, 18))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modeItemStateChanged
        if(mode.getSelectedItem().toString()=="CASH" && evt.getStateChange()==2){
            card.setVisible(false);
            cheque.setVisible(false);
            cash.setVisible(true);
        }else if(mode.getSelectedItem().toString()=="CARD" && evt.getStateChange()==2){
            cheque.setVisible(false);
            cash.setVisible(false);
            card.setVisible(true);
        }else if(mode.getSelectedItem().toString()=="CHEQUE" && evt.getStateChange()==2){
            card.setVisible(false);
            cash.setVisible(false);
            cheque.setVisible(true);
        }
        
    }//GEN-LAST:event_modeItemStateChanged

    private void cashPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashPayMouseClicked
        try {
            pay();
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cashPayMouseClicked

    private void cardPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPayMouseClicked
        try {
            pay();
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cardPayMouseClicked

    private void chequePayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chequePayMouseClicked
        try {
            pay();
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_chequePayMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void cardNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyTyped
        char v=evt.getKeyChar();
        if(!Character.isDigit(v)||v==KeyEvent.VK_BACKSPACE){
            evt.consume();
        }
    }//GEN-LAST:event_cardNumberKeyTyped

    public void pay() throws SQLException{
        String type=modetype[mode.getSelectedIndex()];
        int pkey;
        Connect c=new Connect();
        Connection con=c.getConnection();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select max(payment_id)+1 as pk from payment");
        pkey=rs.getInt("pk");
        PreparedStatement ps4=con.prepareStatement("insert into payment values(?,?,?,?)");
        ps4.setInt(1, pkey);
        ps4.setInt(2,Integer.parseInt(amount.getText()));
        String d=DateToString.getDate(Pay_Date.getDate().getDate(), Pay_Date.getDate().getMonth(), Pay_Date.getDate().getYear());
        ps4.setString(3,d);
        ps4.setString(4,mode.getSelectedItem().toString());
        ps4.executeUpdate();
        ps4.close();
        st.close();
        rs.close();
        if(PayFlag==1){
        Statement st1=con.createStatement();
        ResultSet rs1=st1.executeQuery("select * from medicines");
        int flag=0;
        while(rs1.next()){
            if(rs1.getString("med_name").equals(med) ){
                flag=1;
                int temp=rs1.getInt("quantity");
                temp+=quantity;
                Statement stq=con.createStatement();
                stq.execute("Update medicines set quantity="+temp+" where med_name='"+med+"'");
                stq.close();
                Statement ste=con.createStatement();
                ste.execute("Update medicines set expiray_date='"+exp+"' where med_name='"+med+"'");
                ste.close();
                st1.close();
                rs1.close();
                break;
            }
        }
        
       
        if(flag==0){
            Statement st2=con.createStatement();
            ResultSet rs2=st2.executeQuery("select max(med_id)+1 as mpkey from medicines");
            int mpkey=rs2.getInt("mpkey");
            st2.close();
            PreparedStatement ps1=con.prepareStatement("Insert into medicines values(?,?,?,?,?,?,?,?)");
            ps1.setInt(1,mpkey);
            ps1.setString(2,med);
            ps1.setInt(3,supplier_id);
            ps1.setInt(4,quantity);
            ps1.setString(5,exp);
            ps1.setString(6,"Not given yet");
            ps1.setString(7,"Not given yet");
            ps1.setString(8,"Not given yet");
            ps1.executeUpdate();
            ps1.close();
        }
        int balance=total-Integer.parseInt(amount.getText());
        
        PreparedStatement ps3=con.prepareStatement("insert into activity values(?,?,?,?,?,?,?)");
        ps3.setInt(1,activity_id);
        ps3.setInt(2,supplier_id);
        ps3.setString(3,med);
        ps3.setInt(4,quantity);
        ps3.setString(5, act_date);
        ps3.setInt(6, total);
        ps3.setInt(7, balance);
        ps3.executeUpdate();
        ps3.close();
        }
        if (PayFlag==2){
        int balance=total-Integer.parseInt(amount.getText());
        
        PreparedStatement ps3=con.prepareStatement("Update Activity set balance=? where activity_id=?");
        ps3.setInt(2,activity_id);
        ps3.setInt(1, balance);
        ps3.executeUpdate();
        ps3.close();
        }
        PreparedStatement pst=con.prepareStatement("insert into ACTIVITY_PAYMENT values(?,?)");
        pst.setInt(1,activity_id);
        pst.setInt(2, pkey);
        pst.execute();
        pst.close();
        
        if (type=="CARD"){
            System.out.println("card");
            PreparedStatement ps5=con.prepareStatement("insert into CARD values(?,?,?,?)");
            ps5.setInt(1,pkey);
            ps5.setString(2,CardType.getSelectedItem().toString());
            ps5.setString(4,bankName.getText());
            ps5.setDouble(3,Double.parseDouble(cardNumber.getText()));
            ps5.execute();
            ps5.close();
        }else if(type=="CHEQUE"){
            System.out.println("cheque");
            PreparedStatement ps6=con.prepareStatement("insert into CHEQUE values(?,?,?)");
            ps6.setInt(1, pkey);
            ps6.setDouble(2,Double.parseDouble(chequeNumber.getText()));
            ps6.setString(3,cBankName.getText());
            ps6.execute();
            ps6.close();
        }
        
        
        con.close();
        this.dispose();
        Controler.mainframe.refreshActivities();
    }
    

    
   public void getWindow(int ac_id,int s_id,String medname,int amou,int quant,String ex,String activity_date){
       PayFlag=1;
       activity_id=ac_id;
       supplier_id=s_id;
       amount_value=amou;
       quantity=quant;
       exp=ex;
       med=medname;
       total=amou;
       act_date=activity_date;
       amount.setText(amount_value.toString());
       this.show();
   }
   
   public void getPayWindow(int ac_id,Integer bal){
       PayFlag=2;
       activity_id=ac_id;
       total=bal;
       amount.setText(bal.toString());
       this.setVisible(true);
   }
   
   
   
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JComboBox<String> CardType;
    private javax.swing.JLabel Close;
    private com.toedter.calendar.JDateChooser Pay_Date;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField bankName;
    private javax.swing.JTextField cBankName;
    private javax.swing.JPanel card;
    private javax.swing.JPanel cardDesk;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JLabel cardPay;
    private javax.swing.JPanel cash;
    private javax.swing.JLabel cashPay;
    private javax.swing.JPanel cheque;
    private javax.swing.JTextField chequeNumber;
    private javax.swing.JLabel chequePay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mode;
    // End of variables declaration//GEN-END:variables
}
