
package com.UI;

import com.controlers.Controler;
import com.dao.Connect;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rishi
 */
public class SupplierEdit extends javax.swing.JFrame {

    
    private int sid,key=0;
    
    public SupplierEdit() {
        initComponents();
        this.setLocationRelativeTo(null);
        Add.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Background = new javax.swing.JPanel();
        Edit_Title = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Form = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        company = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();
        Update = new javax.swing.JLabel();
        website = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Comment = new javax.swing.JTextPane();
        Add = new javax.swing.JLabel();
        Add_Title = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(102, 179, 255));
        Background.setPreferredSize(new java.awt.Dimension(410, 400));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit_Title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Edit_Title.setForeground(new java.awt.Color(255, 255, 255));
        Edit_Title.setText("Edit Supplier's Details");
        Background.add(Edit_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/UI/Icons/icons8_Multiply_32px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        Background.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 11, -1, -1));

        Form.setBackground(new java.awt.Color(255, 255, 255));
        Form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Company:");
        Form.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 39, 132, -1));

        company.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        company.setToolTipText("Company Name");
        company.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });
        Form.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 41, 202, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Phone Number:");
        Form.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, -1, -1));

        phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phone.setToolTipText("Phone no");
        phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        Form.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 164, 202, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Address:");
        Form.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 80, -1, -1));

        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        address.setToolTipText("Address of company");
        address.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jScrollPane1.setViewportView(address);

        Form.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 80, 202, 72));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Fax Number:");
        Form.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Website:");
        Form.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        fax.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fax.setToolTipText("Fax no");
        fax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                faxKeyTyped(evt);
            }
        });
        Form.add(fax, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 198, 202, -1));

        Update.setBackground(new java.awt.Color(102, 179, 255));
        Update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Update.setText("Update");
        Update.setToolTipText("Update data");
        Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update.setOpaque(true);
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        Form.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 105, 39));

        website.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        website.setToolTipText("Website");
        website.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Form.add(website, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 232, 202, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Comments:");
        Form.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 264, -1, -1));

        Comment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Comment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Comment.setToolTipText("Comments");
        Comment.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jScrollPane2.setViewportView(Comment);

        Form.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 264, 202, 72));

        Add.setBackground(new java.awt.Color(102, 179, 255));
        Add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add.setText("Add");
        Add.setToolTipText("Add New Supplier");
        Add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add.setOpaque(true);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Form.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 105, 39));

        Background.add(Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 420));

        Add_Title.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Add_Title.setForeground(new java.awt.Color(255, 255, 255));
        Add_Title.setText("Add New Supplier");
        Background.add(Add_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        
        try {
            Connect c=new Connect();
            Connection con=c.getConnection();
            PreparedStatement ps=con.prepareStatement("Update Suppliers set company=?,address=?,phone_no=?,fax_no=?,website=?,comment=? where supplier_id=?");
            ps.setString(1, company.getText().toUpperCase());
            ps.setString(2, address.getText());
            ps.setString(3, phone.getText());
            ps.setString(4, fax.getText());
            ps.setString(5, website.getText());
            ps.setString(6, Comment.getText());
            ps.setInt(7, sid);
            int j=ps.executeUpdate();
            System.out.println(j);
            ps.close();
            con.close();
            Controler.mainframe.SupplierTable();
            JOptionPane.showMessageDialog(this,"Supplier's Data is updated","Update",JOptionPane.PLAIN_MESSAGE);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SupplierEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateMouseClicked

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
       try {
            Connect c=new Connect();
            Connection con=c.getConnection();
            
            PreparedStatement pst=con.prepareStatement("select max(Supplier_id)+1 as pkey from SUPPLIERS");
            ResultSet r=pst.executeQuery();
            while(r.next()){
                key=r.getInt("pkey");
            }
            pst.close();
            r.close();
            
            System.out.println(key);
            PreparedStatement ps=con.prepareStatement("Insert into  SUPPLIERS values(?,?,?,?,?,?,?)");
            ps.setInt(1,key);
            ps.setString(2, company.getText().toUpperCase());
            ps.setString(3, address.getText());
            ps.setString(4, phone.getText());
            ps.setString(5, fax.getText());
            ps.setString(6, website.getText());
            ps.setString(7, Comment.getText());
            int j=ps.executeUpdate();
            System.out.println(j);
            ps.close();
            con.close();
            JOptionPane.showMessageDialog(this,"New Supplier is added" ,"Add",JOptionPane.PLAIN_MESSAGE);
            Controler.mainframe.refreshSupplier();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SupplierEdit.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_AddMouseClicked

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        char v=evt.getKeyChar();
        if(!Character.isDigit(v)||v==KeyEvent.VK_BACKSPACE){
            evt.consume();
        }
    }//GEN-LAST:event_phoneKeyTyped

    private void faxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxKeyTyped
        char v=evt.getKeyChar();
        if(!Character.isDigit(v)||v==KeyEvent.VK_BACKSPACE){
            evt.consume();
        }
    }//GEN-LAST:event_faxKeyTyped

   
    
    public void getEditWindow(int supplier_id,String comp,String add,String phoneno,String faxno,String site,String comments){
        Edit_Title.setVisible(true);
        Add_Title.setVisible(false);
        sid=supplier_id;
        company.setText(comp);
        address.setText(add);
        phone.setText(phoneno);
        fax.setText(faxno);
        website.setText(site);
        Comment.setText(comments);
        this.setVisible(true);
    }
    
    public void getAddWindow(){
        Add_Title.setVisible(true);
        Edit_Title.setVisible(false);
        Update.setVisible(false);
        Add.setVisible(true);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add_Title;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Close;
    private javax.swing.JTextPane Comment;
    private javax.swing.JLabel Edit_Title;
    private javax.swing.JPanel Form;
    private javax.swing.JLabel Update;
    private javax.swing.JTextPane address;
    private javax.swing.JTextField company;
    private javax.swing.JTextField fax;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField website;
    // End of variables declaration//GEN-END:variables
}
